#!/usr/bin/env node
/**
 * dist-branch.mjs — put the released package on the `dist` branch (D47).
 *
 * `master` carries sources: `lib/` is build output, and a git install of master
 * would ask the reader to approve a build and download the development
 * dependencies first. This script packs the package exactly as npm publishes it
 * — `npm pack` builds through `prepublishOnly`, so both come from one build —
 * and writes those files as a single commit on an orphan `dist` branch. The
 * version tag then points at that commit, so a tag install gets the built
 * package too. `--push` sends the branch and the tag to origin.
 *
 * The release workflow runs on the tag's own push, so the tag usually exists
 * already and points at the release commit: this script moves it onto the dist
 * commit, which is what makes the two install paths one artifact.
 *
 * The commit is made with plumbing against a scratch index, so the working tree
 * and the checked-out branch are never touched.
 *
 * Usage: node scripts/dist-branch.mjs [--push]
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const DEBUG = path.join(ROOT, '.debug', 'dist')
const PACK = path.join(DEBUG, 'pack')
const TREE = path.join(DEBUG, 'tree')
const INDEX = path.join(DEBUG, 'index')

/** Run one command to completion and return its stdout. */
function run(command, args, options = {}) {
  // Through a shell, so npm resolves to npm.cmd on Windows; arguments are quoted here.
  const quote = (value) => /[\s"]/.test(value) ? `"${value.replace(/"/g, '\\"')}"` : value
  const line = [command, ...args.map(quote)].join(' ')
  return execFileSync(line, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'], shell: true, ...options }).trim()
}

/** Run one git command against the scratch index and the packed tree. */
function git(args) {
  return run('git', args, {
    cwd: TREE,
    env: { ...process.env, GIT_DIR: path.join(ROOT, '.git'), GIT_WORK_TREE: TREE, GIT_INDEX_FILE: INDEX },
  })
}

const version = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version
const tag = `v${version}`
fs.rmSync(DEBUG, { recursive: true, force: true })
fs.mkdirSync(PACK, { recursive: true })
fs.mkdirSync(TREE, { recursive: true })

// The tarball is the npm package: its file list, its manifest and its build.
const packed = run('npm', ['pack', '--pack-destination', PACK]).split('\n').pop()
run('tar', ['-xzf', path.join(PACK, packed), '-C', TREE, '--strip-components=1'])

// One release per version: a tag that already exists is the release commit this
// run is publishing, and it moves onto the dist commit below. A tag that exists
// on another branch of history is another release, and the version must move.
const existing = run('git', ['tag', '--list', tag])
const ancestor = existing === '' ? true : (() => {
  try {
    run('git', ['merge-base', '--is-ancestor', `${tag}^{commit}`, 'HEAD'])
    return true
  } catch {
    return false
  }
})()
if (existing !== '' && !ancestor) throw new Error(`dist: ${tag} exists outside this history; bump the version before releasing`)

// One commit on an orphan branch: the branch carries the package, no history.
git(['read-tree', '--empty'])
git(['add', '--all'])
const tree = git(['write-tree'])
const commit = git(['commit-tree', tree, '-m', `chore(release): ${tag}\n\nGenerated by scripts/dist-branch.mjs from the ${tag} sources; the files are the npm package's own contents.`])
git(['update-ref', 'refs/heads/dist', commit])
// The tag follows the artifact: a tag install must get the same files npm got.
git(['tag', '--force', tag, commit])
console.log(`dist: tag ${tag} now points at ${commit.slice(0, 8)} (the packaged commit, not the release commit)`)
const files = git(['ls-tree', '--name-only', 'refs/heads/dist']).split('\n')
console.log(`dist: ${files.length} entries at ${commit.slice(0, 8)} (${tag})`)
for (const file of files) console.log(`  ${file}`)

if (process.argv.includes('--push')) {
  run('git', ['push', '--force', 'origin', 'refs/heads/dist:refs/heads/dist'])
  // The tag moved onto the packaged commit, so the push replaces it.
  run('git', ['push', '--force', 'origin', `refs/tags/${tag}`])
  console.log(`dist: pushed refs/heads/dist and ${tag}`)
} else {
  console.log('dist: branch and tag written locally; pass --push to send them')
}
